In [33]:
%load_ext autoreload
%autoreload 2
import sys, os
parent_dir = os.path.abspath(os.path.join(os.path.dirname("..."), "..."))
sys.path.append(parent_dir)
import pandas as pd

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [34]:
# read csv file
train_df = pd.read_csv('../dataset/Train.csv')
train_df

,responseId,view_label,ID_enter,ID_exit,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,congestion_enter_rating,congestion_exit_rating,time_segment_id,cycle_phase
0,zYkHaeOdB7XOnvgP3YW5kQs,Norman Niles #1,time_segment_0_Norman Niles #1_congestion_ente...,time_segment_0_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-00-45.mp4,2025-10-20 06:00:45,2025-10-20 06:00:45,2025-10-20 06:01:44,2025-10-20,none,free flowing,free flowing,0,train
1,NYsHaeCRLq-vnvgPjoXZqA0,Norman Niles #1,time_segment_1_Norman Niles #1_congestion_ente...,time_segment_1_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-01-45.mp4,2025-10-20 06:01:45,2025-10-20 06:01:45,2025-10-20 06:02:44,2025-10-20,none,free flowing,free flowing,1,train
2,A40HaYT8KNm7nvgPq8e12AU,Norman Niles #1,time_segment_2_Norman Niles #1_congestion_ente...,time_segment_2_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-02-45.mp4,2025-10-20 06:02:45,2025-10-20 06:02:45,2025-10-20 06:03:00,2025-10-20,none,free flowing,free flowing,2,train
3,EIsHaanDMK-vnvgPjoXZqA0,Norman Niles #1,time_segment_3_Norman Niles #1_congestion_ente...,time_segment_3_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-03-45.mp4,2025-10-20 06:03:45,2025-10-20 06:03:45,2025-10-20 06:04:44,2025-10-20,none,free flowing,free flowing,3,train
4,RYsHafSeMaqpmecP5vCV0AQ,Norman Niles #1,time_segment_4_Norman Niles #1_congestion_ente...,time_segment_4_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-04-45.mp4,2025-10-20 06:04:45,2025-10-20 06:04:45,2025-10-20 06:04:59,2025-10-20,none,free flowing,free flowing,4,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16071,0YkHacyJMq-vnvgPjoXZqA0,Norman Niles #4,time_segment_4982_Norman Niles #4_congestion_e...,time_segment_4982_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-55-45.mp4,2025-10-26 17:55:45,2025-10-26 17:55:40,2025-10-26 17:56:40,2025-10-26,low,moderate delay,free flowing,4982,train
16072,PYoHaan6Lb-envgP6uGTmAE,Norman Niles #4,time_segment_4983_Norman Niles #4_congestion_e...,time_segment_4983_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-56-45.mp4,2025-10-26 17:56:45,2025-10-26 17:56:41,2025-10-26 17:57:59,2025-10-26,high,moderate delay,free flowing,4983,train
16073,7ooHafDLFdP_ld8Piv3HsQo,Norman Niles #4,time_segment_4984_Norman Niles #4_congestion_e...,time_segment_4984_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-57-45.mp4,2025-10-26 17:57:45,2025-10-26 17:57:42,2025-10-26 17:58:00,2025-10-26,medium,light delay,free flowing,4984,train
16074,0okHabnnG-K2nvgPsZGZ4Aw,Norman Niles #4,time_segment_4985_Norman Niles #4_congestion_e...,time_segment_4985_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-58-45.mp4,2025-10-26 17:58:45,2025-10-26 17:58:42,2025-10-26 17:59:57,2025-10-26,none,light delay,free flowing,4985,train
16075,aYwHae2SDrXOnvgP3YW5kQs,Norman Niles #4,time_segment_4986_Norman Niles #4_congestion_e...,time_segment_4986_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-59-45.mp4,2025-10-26 17:59:45,2025-10-26 17:59:39,2025-10-26 18:00:59,2025-10-26,none,free flowing,free flowing,4986,train

In [9]:
# read csv file
df_consolidated = pd.read_csv('../consolidated_results.csv')
df_consolidated

,filename,camera,date,time,datetime,hour,minute,duration_seconds,fps,total_frames,...,poly_vtype_bus_north_circulating,poly_vtype_bus_north_entry,poly_vtype_bus_north_exit,poly_vtype_car_north_circulating,poly_vtype_car_north_entry,poly_vtype_car_north_exit,poly_vtype_motorcycle_north_circulating,poly_vtype_truck_north_circulating,poly_vtype_truck_north_entry,poly_vtype_truck_north_exit
0,normanniles1_2025-10-20-08-59-45,normanniles1,2025-10-20,08:59:45,2025-10-20 08:59:45,8,59,59.85,20,1197,...,NaN,NaN,NaN,5,2.0,6.0,NaN,1.0,NaN,NaN
1,normanniles1_2025-10-20-09-00-45,normanniles1,2025-10-20,09:00:45,2025-10-20 09:00:45,9,0,59.85,20,1197,...,NaN,NaN,NaN,11,NaN,8.0,NaN,NaN,NaN,NaN
2,normanniles1_2025-10-20-11-44-45,normanniles1,2025-10-20,11:44:45,2025-10-20 11:44:45,11,44,59.85,20,1197,...,NaN,NaN,NaN,177,86.0,24.0,NaN,22.0,NaN,NaN
3,normanniles1_2025-10-20-11-45-45,normanniles1,2025-10-20,11:45:45,2025-10-20 11:45:45,11,45,59.90,20,1198,...,NaN,NaN,NaN,140,46.0,30.0,NaN,23.0,1.0,2.0
4,normanniles1_2025-10-20-14-40-45,normanniles1,2025-10-20,14:40:45,2025-10-20 14:40:45,14,40,59.90,20,1198,...,NaN,NaN,NaN,134,57.0,33.0,NaN,6.0,5.0,1.0
5,normanniles1_2025-10-20-14-41-45,normanniles1,2025-10-20,14:41:45,2025-10-20 14:41:45,14,41,59.85,20,1197,...,19.0,3.0,1.0,110,46.0,23.0,NaN,21.0,11.0,8.0
6,normanniles1_2025-10-21-07-39-45,normanniles1,2025-10-21,07:39:45,2025-10-21 07:39:45,7,39,59.90,20,1198,...,2.0,NaN,NaN,5,NaN,NaN,NaN,1.0,NaN,1.0
7,normanniles1_2025-10-21-07-40-45,normanniles1,2025-10-21,07:40:45,2025-10-21 07:40:45,7,40,59.90,20,1198,...,NaN,NaN,NaN,10,1.0,1.0,NaN,NaN,NaN,NaN
8,normanniles1_2025-10-21-10-16-45,normanniles1,2025-10-21,10:16:45,2025-10-21 10:16:45,10,16,59.85,20,1197,...,2.0,2.0,NaN,110,24.0,10.0,NaN,16.0,6.0,1.0
9,normanniles1_2025-10-21-10-17-45,normanniles1,2025-10-21,10:17:45,2025-10-21 10:17:45,10,17,59.85,20,1197,...,4.0,NaN,NaN,61,38.0,11.0,NaN,9.0,4.0,NaN
10,normanniles1_2025-10-21-14-37-45,normanniles1,2025-10-21,14:37:45,2025-10-21 14:37:45,14,37,59.90,20,1198,...,NaN,NaN,NaN,120,19.0,30.0,NaN,20.0,2.0,5.0
11,normanniles1_2025-10-21-14-38-45,normanniles1,2025-10-21,14:38:45,2025-10-21 14:38:45,14,38,59.95,20,1199,...,2.0,NaN,NaN,119,32.0,43.0,NaN,26.0,4.0,4.0
12,normanniles1_2025-10-22-09-18-45,normanniles1,2025-10-22,09:18:45,2025-10-22 09:18:45,9,18,59.85,20,1197,...,NaN,NaN,NaN,22,1.0,NaN,NaN,3.0,NaN,NaN
13,normanniles1_2025-10-22-09-19-45,normanniles1,2025-10-22,09:19:45,2025-10-22 09:19:45,9,19,59.90,20,1198,...,NaN,NaN,NaN,7,3.0,2.0,NaN,NaN,NaN,NaN
14,normanniles1_2025-10-22-13-16-45,normanniles1,2025-10-22,13:16:45,2025-10-22 13:16:45,13,16,60.00,20,1200,...,7.0,NaN,NaN,149,41.0,26.0,NaN,18.0,4.0,NaN
15,normanniles1_2025-10-22-13-17-45,normanniles1,2025-10-22,13:17:45,2025-10-22 13:17:45,13,17,59.85,20,1197,...,1.0,NaN,NaN,103,26.0,46.0,NaN,24.0,9.0,NaN
16,normanniles1_2025-10-22-17-09-45,normanniles1,2025-10-22,17:09:45,2025-10-22 17:09:45,17,9,59.95,20,1199,...,7.0,1.0,NaN,109,47.0,35.0,1.0,40.0,10.0,4.0
17,normanniles1_2025-10-22-17-10-45,normanniles1,2025-10-22,17:10:45,2025-10-22 17:10:45,17,10,59.90,20,1198,...,NaN,NaN,2.0,127,31.0,29.0,NaN,15.0,1.0,3.0
18,normanniles1_2025-10-23-07-32-45,normanniles1,2025-10-23,07:32:45,2025-10-23 07:32:45,7,32,59.85,20,1197,...,NaN,NaN,NaN,2,2.0,NaN,NaN,NaN,NaN,NaN
19,normanniles1_2025-10-23-07-33-45,normanniles1,2025-10-23,07:33:45,2025-10-23 07:33:45,7,33,59.90,20,1198,...,NaN,NaN,NaN,6,3.0,3.0,NaN,NaN,NaN,NaN

In [37]:
df_consolidated

,filename,camera,date,time,datetime,hour,minute,duration_seconds,fps,total_frames,...,poly_vtype_bus_north_entry,poly_vtype_bus_north_exit,poly_vtype_car_north_circulating,poly_vtype_car_north_entry,poly_vtype_car_north_exit,poly_vtype_motorcycle_north_circulating,poly_vtype_truck_north_circulating,poly_vtype_truck_north_entry,poly_vtype_truck_north_exit,videos
0,normanniles1_2025-10-20-08-59-45,normanniles1,2025-10-20,08:59:45,2025-10-20 08:59:45,8,59,59.85,20,1197,...,NaN,NaN,5,2.0,6.0,NaN,1.0,NaN,NaN,normanniles1/normanniles1_2025-10-20-08-59-45.mp4
1,normanniles1_2025-10-20-09-00-45,normanniles1,2025-10-20,09:00:45,2025-10-20 09:00:45,9,0,59.85,20,1197,...,NaN,NaN,11,NaN,8.0,NaN,NaN,NaN,NaN,normanniles1/normanniles1_2025-10-20-09-00-45.mp4
2,normanniles1_2025-10-20-11-44-45,normanniles1,2025-10-20,11:44:45,2025-10-20 11:44:45,11,44,59.85,20,1197,...,NaN,NaN,177,86.0,24.0,NaN,22.0,NaN,NaN,normanniles1/normanniles1_2025-10-20-11-44-45.mp4
3,normanniles1_2025-10-20-11-45-45,normanniles1,2025-10-20,11:45:45,2025-10-20 11:45:45,11,45,59.90,20,1198,...,NaN,NaN,140,46.0,30.0,NaN,23.0,1.0,2.0,normanniles1/normanniles1_2025-10-20-11-45-45.mp4
4,normanniles1_2025-10-20-14-40-45,normanniles1,2025-10-20,14:40:45,2025-10-20 14:40:45,14,40,59.90,20,1198,...,NaN,NaN,134,57.0,33.0,NaN,6.0,5.0,1.0,normanniles1/normanniles1_2025-10-20-14-40-45.mp4
5,normanniles1_2025-10-20-14-41-45,normanniles1,2025-10-20,14:41:45,2025-10-20 14:41:45,14,41,59.85,20,1197,...,3.0,1.0,110,46.0,23.0,NaN,21.0,11.0,8.0,normanniles1/normanniles1_2025-10-20-14-41-45.mp4
6,normanniles1_2025-10-21-07-39-45,normanniles1,2025-10-21,07:39:45,2025-10-21 07:39:45,7,39,59.90,20,1198,...,NaN,NaN,5,NaN,NaN,NaN,1.0,NaN,1.0,normanniles1/normanniles1_2025-10-21-07-39-45.mp4
7,normanniles1_2025-10-21-07-40-45,normanniles1,2025-10-21,07:40:45,2025-10-21 07:40:45,7,40,59.90,20,1198,...,NaN,NaN,10,1.0,1.0,NaN,NaN,NaN,NaN,normanniles1/normanniles1_2025-10-21-07-40-45.mp4
8,normanniles1_2025-10-21-10-16-45,normanniles1,2025-10-21,10:16:45,2025-10-21 10:16:45,10,16,59.85,20,1197,...,2.0,NaN,110,24.0,10.0,NaN,16.0,6.0,1.0,normanniles1/normanniles1_2025-10-21-10-16-45.mp4
9,normanniles1_2025-10-21-10-17-45,normanniles1,2025-10-21,10:17:45,2025-10-21 10:17:45,10,17,59.85,20,1197,...,NaN,NaN,61,38.0,11.0,NaN,9.0,4.0,NaN,normanniles1/normanniles1_2025-10-21-10-17-45.mp4
10,normanniles1_2025-10-21-14-37-45,normanniles1,2025-10-21,14:37:45,2025-10-21 14:37:45,14,37,59.90,20,1198,...,NaN,NaN,120,19.0,30.0,NaN,20.0,2.0,5.0,normanniles1/normanniles1_2025-10-21-14-37-45.mp4
11,normanniles1_2025-10-21-14-38-45,normanniles1,2025-10-21,14:38:45,2025-10-21 14:38:45,14,38,59.95,20,1199,...,NaN,NaN,119,32.0,43.0,NaN,26.0,4.0,4.0,normanniles1/normanniles1_2025-10-21-14-38-45.mp4
12,normanniles1_2025-10-22-09-18-45,normanniles1,2025-10-22,09:18:45,2025-10-22 09:18:45,9,18,59.85,20,1197,...,NaN,NaN,22,1.0,NaN,NaN,3.0,NaN,NaN,normanniles1/normanniles1_2025-10-22-09-18-45.mp4
13,normanniles1_2025-10-22-09-19-45,normanniles1,2025-10-22,09:19:45,2025-10-22 09:19:45,9,19,59.90,20,1198,...,NaN,NaN,7,3.0,2.0,NaN,NaN,NaN,NaN,normanniles1/normanniles1_2025-10-22-09-19-45.mp4
14,normanniles1_2025-10-22-13-16-45,normanniles1,2025-10-22,13:16:45,2025-10-22 13:16:45,13,16,60.00,20,1200,...,NaN,NaN,149,41.0,26.0,NaN,18.0,4.0,NaN,normanniles1/normanniles1_2025-10-22-13-16-45.mp4
15,normanniles1_2025-10-22-13-17-45,normanniles1,2025-10-22,13:17:45,2025-10-22 13:17:45,13,17,59.85,20,1197,...,NaN,NaN,103,26.0,46.0,NaN,24.0,9.0,NaN,normanniles1/normanniles1_2025-10-22-13-17-45.mp4
16,normanniles1_2025-10-22-17-09-45,normanniles1,2025-10-22,17:09:45,2025-10-22 17:09:45,17,9,59.95,20,1199,...,1.0,NaN,109,47.0,35.0,1.0,40.0,10.0,4.0,normanniles1/normanniles1_2025-10-22-17-09-45.mp4
17,normanniles1_2025-10-22-17-10-45,normanniles1,2025-10-22,17:10:45,2025-10-22 17:10:45,17,10,59.90,20,1198,...,NaN,2.0,127,31.0,29.0,NaN,15.0,1.0,3.0,normanniles1/normanniles1_2025-10-22-17-10-45.mp4
18,normanniles1_2025-10-23-07-32-45,normanniles1,2025-10-23,07:32:45,2025-10-23 07:32:45,7,32,59.85,20,1197,...,NaN,NaN,2,2.0,NaN,NaN,NaN,NaN,NaN,normanniles1/normanniles1_2025-10-23-07-32-45.mp4
19,normanniles1_2025-10-23-07-33-45,normanniles1,2025-10-23,07:33:45,2025-10-23 07:33:45,7,33,59.90,20,1198,...,NaN,NaN,6,3.0,3.0,NaN,NaN,NaN,NaN,normanniles1/normanniles1_2025-10-23-07-33-45.mp4

In [31]:
df_consolidated["videos"] = df_consolidated["camera"] + '/' + df_consolidated["filename"] + '.mp4'

In [29]:
train_df[["videos"]].iloc[0].values[0]

'normanniles1/normanniles1_2025-10-20-06-00-45.mp4'

In [30]:
df_consolidated[["videos"]].iloc[0].values[0]

'normanniles1/normanniles1_2025-10-20-08-59-45'

In [38]:
# merge the two dataframes on videos column
merged_df = pd.merge(train_df, df_consolidated, on='videos', how='inner')
merged_df

,responseId,view_label,ID_enter,ID_exit,videos,video_time,datetimestamp_start,datetimestamp_end,date_x,signaling,...,poly_vtype_bus_north_circulating,poly_vtype_bus_north_entry,poly_vtype_bus_north_exit,poly_vtype_car_north_circulating,poly_vtype_car_north_entry,poly_vtype_car_north_exit,poly_vtype_motorcycle_north_circulating,poly_vtype_truck_north_circulating,poly_vtype_truck_north_entry,poly_vtype_truck_north_exit
0,04kHaYDsKJ__698PweWaiQ4,Norman Niles #1,time_segment_179_Norman Niles #1_congestion_en...,time_segment_179_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-08-59-45.mp4,2025-10-20 08:59:45,2025-10-20 08:59:45,2025-10-20 09:00:44,2025-10-20,none,...,NaN,NaN,NaN,5,2.0,6.0,NaN,1.0,NaN,NaN
1,AIsHaZeCH7zA698P_KuO8AM,Norman Niles #1,time_segment_180_Norman Niles #1_congestion_en...,time_segment_180_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-09-00-45.mp4,2025-10-20 09:00:45,2025-10-20 09:00:45,2025-10-20 09:01:00,2025-10-20,none,...,NaN,NaN,NaN,11,NaN,8.0,NaN,NaN,NaN,NaN
2,_4wHadfNC7Ov3NoPq7G46QE,Norman Niles #1,time_segment_342_Norman Niles #1_congestion_en...,time_segment_342_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-11-44-45.mp4,2025-10-20 11:44:45,2025-10-20 11:44:44,2025-10-20 11:45:44,2025-10-20,medium,...,NaN,NaN,NaN,177,86.0,24.0,NaN,22.0,NaN,NaN
3,I40HacHGKKHXnvgP76fxyQI,Norman Niles #1,time_segment_343_Norman Niles #1_congestion_en...,time_segment_343_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-11-45-45.mp4,2025-10-20 11:45:45,2025-10-20 11:45:44,2025-10-20 11:46:44,2025-10-20,low,...,NaN,NaN,NaN,140,46.0,30.0,NaN,23.0,1.0,2.0
4,WIoHaai-DrHZnvgPgt-ZqQs,Norman Niles #1,time_segment_516_Norman Niles #1_congestion_en...,time_segment_516_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-14-40-45.mp4,2025-10-20 14:40:45,2025-10-20 14:40:44,2025-10-20 14:41:43,2025-10-20,medium,...,NaN,NaN,NaN,134,57.0,33.0,NaN,6.0,5.0,1.0
5,8IwHabO1MOaQ2PgPqvKU8As,Norman Niles #1,time_segment_517_Norman Niles #1_congestion_en...,time_segment_517_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-14-41-45.mp4,2025-10-20 14:41:45,2025-10-20 14:41:44,2025-10-20 14:42:44,2025-10-20,low,...,19.0,3.0,1.0,110,46.0,23.0,NaN,21.0,11.0,8.0
6,7YoHabyDMZKdmecPt_3RiQ4,Norman Niles #1,time_segment_812_Norman Niles #1_congestion_en...,time_segment_812_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-21-07-39-45.mp4,2025-10-21 07:39:45,2025-10-21 07:39:45,2025-10-21 07:40:44,2025-10-21,none,...,2.0,NaN,NaN,5,NaN,NaN,NaN,1.0,NaN,1.0
7,AYoHaebpMfK1ld8PufLf6AI,Norman Niles #1,time_segment_813_Norman Niles #1_congestion_en...,time_segment_813_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-21-07-40-45.mp4,2025-10-21 07:40:45,2025-10-21 07:40:45,2025-10-21 07:41:44,2025-10-21,none,...,NaN,NaN,NaN,10,1.0,1.0,NaN,NaN,NaN,NaN
8,KYsHaYfkEJSgmecP8YHv4Qc,Norman Niles #1,time_segment_969_Norman Niles #1_congestion_en...,time_segment_969_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-21-10-16-45.mp4,2025-10-21 10:16:45,2025-10-21 10:16:45,2025-10-21 10:17:44,2025-10-21,none,...,2.0,2.0,NaN,110,24.0,10.0,NaN,16.0,6.0,1.0
9,8owHafO_DsjtnvgP8NiHuAw,Norman Niles #1,time_segment_970_Norman Niles #1_congestion_en...,time_segment_970_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-21-10-17-45.mp4,2025-10-21 10:17:45,2025-10-21 10:17:45,2025-10-21 10:18:45,2025-10-21,none,...,4.0,NaN,NaN,61,38.0,11.0,NaN,9.0,4.0,NaN
10,c48HacOmHKHXnvgP76fxyQI,Norman Niles #1,time_segment_1223_Norman Niles #1_congestion_e...,time_segment_1223_Norman Niles #1_congestion_e...,normanniles1/normanniles1_2025-10-21-14-37-45.mp4,2025-10-21 14:37:45,2025-10-21 14:37:44,2025-10-21 14:38:43,2025-10-21,low,...,NaN,NaN,NaN,120,19.0,30.0,NaN,20.0,2.0,5.0
11,0YkHab3pJ6HXnvgP76fxyQI,Norman Niles #1,time_segment_1224_Norman Niles #1_congestion_e...,time_segment_1224_Norman Niles #1_congestion_e...,normanniles1/normanniles1_2025-10-21-14-38-45.mp4,2025-10-21 14:38:45,2025-10-21 14:38:44,2025-10-21 14:39:43,2025-10-21,low,...,2.0,NaN,NaN,119,32.0,43.0,NaN,26.0,4.0,4.0
12,A4oHaYnVAbHZnvgPgt-ZqQs,Norman Niles #1,time_segment_1622_Norman Niles #1_congestion_e...,time_segment_1622_Norman Niles #1_congestion_e...,normanniles1/normanniles1_2025-10-22-09-18-45.mp4,2025-10-22 09:18:45,2025-10-22 09:18:45,2025-10-22 09:19:44,2025-10-22,none,...,NaN,NaN,NaN,22,1.0,NaN,NaN,3.0,NaN,NaN
13,AYoHaf_ALLeLqMgP4oDE8Aw,Norman Niles #1,time_segment_1623_Norman Niles #1_congestion_e...,time_segment_1623_Norman Niles #1_congestion_e...,normanniles1/normanniles1_2025-10-22-09-19-45.mp4,2025-10-22 09:19:45,2025-10-22 09:19:45,2025-10-22 09:20:44,2025-10-22,none,...,NaN,NaN,NaN,7,3.0,2.0,NaN,NaN,NaN,NaN
14,24wHaYC9BMjtnvgP8NiHuAw,Norman Niles #1,time_segment_1859_Norman Niles #1_congestion_e...,time_segment_1859_Norman Niles #1_congestion_e...,normanniles1/normanniles1_2025-10-22-13-16-45.mp4,2025-10-22 13:16:45,2025-10-22 13:16:42,2025-10-22 13:17:41,2025-10-22,none,...,7.0,NaN,NaN,149,41.0,26.0,NaN,18.0,4.0,NaN
15,0YkHabGVPPK1ld8PufLf6AI,Norman Niles #1,time_segment_1860_Norman Niles #1_congestion_e...,time_segment_1860_Norman Niles #1_congestion_e...,normanniles1/normanniles1_2025-10-22-13-17-45.mp4,2025-10-22 13:17:45,2025-10-22 13:17:42,2025-10-22 13:18:41,2025-10-22,low,...,1.0,NaN,NaN,103,26.0,46.0,NaN,24.0,9.0,NaN
16,_osHafDPIsjtnvgP8NiHuAw,Norman Niles #1,time_segment_2090_Norman Niles #1_congestion_e...,time_segment_2090_Norman Niles #1_congestion_e...,normanniles1/normanniles1_2025-10-22-17-09-45.mp4,2025-10-22 17:09:45,2025-10-22 17:09:41,2025-10-22 17:10:40,2025-10-22,medium,...,7.0,1.0,NaN,109,47.0,35.0,1.0,40.0,10.0,4.0
17,BIoHaeHNK5ehmecPss7LwQo,Norman Niles #1,time_segment_2091_Norman Niles #1_congestion_e...,time_segment_2091_Norman Niles #1_congestion_e...,normanniles1/normanniles1_2025-10-22-17-10-45.mp4,2025-10-22 17:10:45,2025-10-22 17:10:41,2025-10-22 17:11:40,2025-10-22,low,...,NaN,NaN,2.0,127,31.0,29.0,NaN,15.0,1.0,3.0
18,AooHafPuF6HXnvgP76fxyQI,Norman Niles #1,time_segment_2232_Norman Niles #1_congestion_e...,time_segment_2232_Norman Niles #1_congestion_e...,normanniles1/normanniles1_2025-10-23-07-32-45.mp4,2025-10-23 07:32:45,2025-10-23 07:32:45,2025-10-23 07:33:45,2025-10-23,none,...,NaN,NaN,NaN,2,2.0,NaN,NaN,NaN,NaN,NaN
19,0YkHabDwLLHZnvgPgt-ZqQs,Norman Niles #1,time_segment_2233_Norman Niles #1_congestion_e...,time_segment_2233_Norman Niles #1_congestion_e...,normanniles1/normanniles1_2025-10-23-07-33-45.mp4,2025-10-23 07:33:45,2025-10-23 07:33:45,2025-10-23 07:34:45,2025-10-23,none,...,NaN,NaN,NaN,6,3.0,3.0,NaN,NaN,NaN,NaN

In [42]:
merged_df.vehicle_class_car

0       9
1      14
2     149
3     112
4     119
5     129
6       6
7       8
8      64
9      64
10    100
11    109
12     11
13      7
14    129
15    106
16    126
17    123
18      2
19      7
Name: vehicle_class_car, dtype: int64

In [40]:
merged_df.columns.tolist()

['responseId',
 'view_label',
 'ID_enter',
 'ID_exit',
 'videos',
 'video_time',
 'datetimestamp_start',
 'datetimestamp_end',
 'date_x',
 'signaling',
 'congestion_enter_rating',
 'congestion_exit_rating',
 'time_segment_id',
 'cycle_phase',
 'filename',
 'camera',
 'date_y',
 'time',
 'datetime',
 'hour',
 'minute',
 'duration_seconds',
 'fps',
 'total_frames',
 'video_width',
 'video_height',
 'total_vehicles_tracked',
 'source_file',
 'video_path',
 'zone_count_north_circulating',
 'zone_count_north_entry',
 'zone_count_north_exit',
 'dwell_count_north_circulating',
 'dwell_count_north_entry',
 'dwell_count_north_exit',
 'dwell_max_north_circulating',
 'dwell_max_north_entry',
 'dwell_max_north_exit',
 'dwell_mean_north_circulating',
 'dwell_mean_north_entry',
 'dwell_mean_north_exit',
 'dwell_median_north_circulating',
 'dwell_median_north_entry',
 'dwell_median_north_exit',
 'dwell_min_north_circulating',
 'dwell_min_north_entry',
 'dwell_min_north_exit',
 'dwell_std_north_circulating',
 'dwell_std_north_entry',
 'dwell_std_north_exit',
 'vehicle_class_bus',
 'vehicle_class_car',
 'vehicle_class_motorcycle',
 'vehicle_class_truck',
 'avg_journey_duration',
 'max_journey_duration',
 'min_journey_duration',
 'avg_zones_visited',
 'max_zones_visited',
 'poly_conf_mean_north_circulating',
 'poly_conf_mean_north_entry',
 'poly_conf_mean_north_exit',
 'poly_conf_median_north_circulating',
 'poly_conf_median_north_entry',
 'poly_conf_median_north_exit',
 'poly_dur_mean_north_circulating',
 'poly_dur_mean_north_entry',
 'poly_dur_mean_north_exit',
 'poly_dur_median_north_circulating',
 'poly_dur_median_north_entry',
 'poly_dur_median_north_exit',
 'poly_dur_std_north_circulating',
 'poly_dur_std_north_entry',
 'poly_dur_std_north_exit',
 'poly_size_mean_north_circulating',
 'poly_size_mean_north_entry',
 'poly_size_mean_north_exit',
 'poly_size_median_north_circulating',
 'poly_size_median_north_entry',
 'poly_size_median_north_exit',
 'poly_size_std_north_circulating',
 'poly_size_std_north_entry',
 'poly_size_std_north_exit',
 'poly_speed_mean_north_circulating',
 'poly_speed_mean_north_entry',
 'poly_speed_mean_north_exit',
 'poly_speed_median_north_circulating',
 'poly_speed_median_north_entry',
 'poly_speed_median_north_exit',
 'poly_speed_std_north_circulating',
 'poly_speed_std_north_entry',
 'poly_speed_std_north_exit',
 'poly_throughput_north_circulating',
 'poly_throughput_north_entry',
 'poly_throughput_north_exit',
 'poly_total_visits_north_circulating',
 'poly_total_visits_north_entry',
 'poly_total_visits_north_exit',
 'poly_unique_vehicles_north_circulating',
 'poly_unique_vehicles_north_entry',
 'poly_unique_vehicles_north_exit',
 'poly_vtype_bus_north_circulating',
 'poly_vtype_bus_north_entry',
 'poly_vtype_bus_north_exit',
 'poly_vtype_car_north_circulating',
 'poly_vtype_car_north_entry',
 'poly_vtype_car_north_exit',
 'poly_vtype_motorcycle_north_circulating',
 'poly_vtype_truck_north_circulating',
 'poly_vtype_truck_north_entry',
 'poly_vtype_truck_north_exit']

In [10]:
from astral import LocationInfo
from astral.sun import sun
from datetime import datetime, time
import pytz

# Barbados location (approximate coordinates for Bridgetown)
barbados = LocationInfo("Barbados", "Caribbean", "America/Barbados", 13.1939, -59.5432)

def get_sun_times(date):
    """Get sunrise and sunset times for a given date in Barbados"""
    s = sun(barbados.observer, date=date, tzinfo=pytz.timezone('America/Barbados'))
    return s['sunrise'].time(), s['sunset'].time()

def classify_time_period(dt):
    """
    Classify time into period of day
    - Night: sunset to sunrise
    - Morning: sunrise to 12:00
    - Afternoon: 12:00 to 17:00
    - Evening: 17:00 to sunset
    """
    if isinstance(dt, str):
        dt = pd.to_datetime(dt)
    
    date = dt.date()
    time_of_day = dt.time()
    
    sunrise, sunset = get_sun_times(date)
    
    # Determine if it's day or night
    if time_of_day < sunrise or time_of_day >= sunset:
        day_night = 'night'
    else:
        day_night = 'day'
    
    # Determine period of day
    if time_of_day < sunrise:
        period = 'night'
    elif sunrise <= time_of_day < time(12, 0):
        period = 'morning'
    elif time(12, 0) <= time_of_day < time(17, 0):
        period = 'afternoon'
    elif time(17, 0) <= time_of_day < sunset:
        period = 'evening'
    else:
        period = 'night'
    
    return day_night, period, sunrise, sunset

# Test with a sample datetime
test_date = datetime(2025, 10, 20, 14, 30)
day_night, period, sunrise, sunset = classify_time_period(test_date)
print(f"Test: {test_date}")
print(f"Sunrise: {sunrise}, Sunset: {sunset}")
print(f"Day/Night: {day_night}, Period: {period}")

Test: 2025-10-20 14:30:00
Sunrise: 05:49:33.762520, Sunset: 17:35:59.528994
Day/Night: day, Period: afternoon

In [ ]:
# Apply to your dataframe
# First, let's check what columns exist in merged_df
print("Columns in merged_df:", merged_df.columns.tolist())
merged_df.head()

In [ ]:
# Create a datetime column by combining date and time columns
# Assuming your dataframe has 'date' and 'time' columns, adjust as needed
# Example: merged_df['datetime'] = pd.to_datetime(merged_df['date'] + ' ' + merged_df['time'])

# Apply the classification function to create new columns
def apply_classification(row):
    """Apply time period classification to a dataframe row"""
    # Adjust this based on your actual datetime column
    # If you have separate date and time columns:
    # dt = pd.to_datetime(f"{row['date']} {row['time']}")
    # If you have a single datetime column:
    # dt = row['datetime']
    
    day_night, period, sunrise, sunset = classify_time_period(row['datetime'])
    return pd.Series({
        'day_night': day_night,
        'period_of_day': period,
        'sunrise': sunrise,
        'sunset': sunset
    })

# Example: Apply to your dataframe
# merged_df[['day_night', 'period_of_day', 'sunrise', 'sunset']] = merged_df.apply(apply_classification, axis=1)
# merged_df.head()