In [1]:
import pandas as pd

In [4]:
# read csv file
df = pd.read_csv('Train.csv')
df

,responseId,view_label,ID_enter,ID_exit,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,congestion_enter_rating,congestion_exit_rating,time_segment_id,cycle_phase
0,zYkHaeOdB7XOnvgP3YW5kQs,Norman Niles #1,time_segment_0_Norman Niles #1_congestion_ente...,time_segment_0_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-00-45.mp4,2025-10-20 06:00:45,2025-10-20 06:00:45,2025-10-20 06:01:44,2025-10-20,none,free flowing,free flowing,0,train
1,NYsHaeCRLq-vnvgPjoXZqA0,Norman Niles #1,time_segment_1_Norman Niles #1_congestion_ente...,time_segment_1_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-01-45.mp4,2025-10-20 06:01:45,2025-10-20 06:01:45,2025-10-20 06:02:44,2025-10-20,none,free flowing,free flowing,1,train
2,A40HaYT8KNm7nvgPq8e12AU,Norman Niles #1,time_segment_2_Norman Niles #1_congestion_ente...,time_segment_2_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-02-45.mp4,2025-10-20 06:02:45,2025-10-20 06:02:45,2025-10-20 06:03:00,2025-10-20,none,free flowing,free flowing,2,train
3,EIsHaanDMK-vnvgPjoXZqA0,Norman Niles #1,time_segment_3_Norman Niles #1_congestion_ente...,time_segment_3_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-03-45.mp4,2025-10-20 06:03:45,2025-10-20 06:03:45,2025-10-20 06:04:44,2025-10-20,none,free flowing,free flowing,3,train
4,RYsHafSeMaqpmecP5vCV0AQ,Norman Niles #1,time_segment_4_Norman Niles #1_congestion_ente...,time_segment_4_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-04-45.mp4,2025-10-20 06:04:45,2025-10-20 06:04:45,2025-10-20 06:04:59,2025-10-20,none,free flowing,free flowing,4,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16071,0YkHacyJMq-vnvgPjoXZqA0,Norman Niles #4,time_segment_4982_Norman Niles #4_congestion_e...,time_segment_4982_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-55-45.mp4,2025-10-26 17:55:45,2025-10-26 17:55:40,2025-10-26 17:56:40,2025-10-26,low,moderate delay,free flowing,4982,train
16072,PYoHaan6Lb-envgP6uGTmAE,Norman Niles #4,time_segment_4983_Norman Niles #4_congestion_e...,time_segment_4983_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-56-45.mp4,2025-10-26 17:56:45,2025-10-26 17:56:41,2025-10-26 17:57:59,2025-10-26,high,moderate delay,free flowing,4983,train
16073,7ooHafDLFdP_ld8Piv3HsQo,Norman Niles #4,time_segment_4984_Norman Niles #4_congestion_e...,time_segment_4984_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-57-45.mp4,2025-10-26 17:57:45,2025-10-26 17:57:42,2025-10-26 17:58:00,2025-10-26,medium,light delay,free flowing,4984,train
16074,0okHabnnG-K2nvgPsZGZ4Aw,Norman Niles #4,time_segment_4985_Norman Niles #4_congestion_e...,time_segment_4985_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-58-45.mp4,2025-10-26 17:58:45,2025-10-26 17:58:42,2025-10-26 17:59:57,2025-10-26,none,light delay,free flowing,4985,train
16075,aYwHae2SDrXOnvgP3YW5kQs,Norman Niles #4,time_segment_4986_Norman Niles #4_congestion_e...,time_segment_4986_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-59-45.mp4,2025-10-26 17:59:45,2025-10-26 17:59:39,2025-10-26 18:00:59,2025-10-26,none,free flowing,free flowing,4986,train

In [7]:
df[df["date"] == "2025-10-20"]

,responseId,view_label,ID_enter,ID_exit,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,congestion_enter_rating,congestion_exit_rating,time_segment_id,cycle_phase
0,zYkHaeOdB7XOnvgP3YW5kQs,Norman Niles #1,time_segment_0_Norman Niles #1_congestion_ente...,time_segment_0_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-00-45.mp4,2025-10-20 06:00:45,2025-10-20 06:00:45,2025-10-20 06:01:44,2025-10-20,none,free flowing,free flowing,0,train
1,NYsHaeCRLq-vnvgPjoXZqA0,Norman Niles #1,time_segment_1_Norman Niles #1_congestion_ente...,time_segment_1_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-01-45.mp4,2025-10-20 06:01:45,2025-10-20 06:01:45,2025-10-20 06:02:44,2025-10-20,none,free flowing,free flowing,1,train
2,A40HaYT8KNm7nvgPq8e12AU,Norman Niles #1,time_segment_2_Norman Niles #1_congestion_ente...,time_segment_2_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-02-45.mp4,2025-10-20 06:02:45,2025-10-20 06:02:45,2025-10-20 06:03:00,2025-10-20,none,free flowing,free flowing,2,train
3,EIsHaanDMK-vnvgPjoXZqA0,Norman Niles #1,time_segment_3_Norman Niles #1_congestion_ente...,time_segment_3_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-03-45.mp4,2025-10-20 06:03:45,2025-10-20 06:03:45,2025-10-20 06:04:44,2025-10-20,none,free flowing,free flowing,3,train
4,RYsHafSeMaqpmecP5vCV0AQ,Norman Niles #1,time_segment_4_Norman Niles #1_congestion_ente...,time_segment_4_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-04-45.mp4,2025-10-20 06:04:45,2025-10-20 06:04:45,2025-10-20 06:04:59,2025-10-20,none,free flowing,free flowing,4,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12633,IYsHad1rn__r3w_B5ZqJDg,Norman Niles #4,time_segment_708_Norman Niles #4_congestion_en...,time_segment_708_Norman Niles #4_congestion_ex...,normanniles4/normanniles4_2025-10-20-17-54-45.mp4,2025-10-20 17:54:45,2025-10-20 17:54:43,2025-10-20 17:55:42,2025-10-20,none,free flowing,free flowing,708,train
12634,0YkHabmCE6HXnvgP76fxyQI,Norman Niles #4,time_segment_709_Norman Niles #4_congestion_en...,time_segment_709_Norman Niles #4_congestion_ex...,normanniles4/normanniles4_2025-10-20-17-55-45.mp4,2025-10-20 17:55:45,2025-10-20 17:55:43,2025-10-20 17:56:42,2025-10-20,none,light delay,free flowing,709,train
12635,d4sHacrSIbmfnvgPoaTSqQ0,Norman Niles #4,time_segment_710_Norman Niles #4_congestion_en...,time_segment_710_Norman Niles #4_congestion_ex...,normanniles4/normanniles4_2025-10-20-17-56-45.mp4,2025-10-20 17:56:45,2025-10-20 17:56:43,2025-10-20 17:57:42,2025-10-20,none,free flowing,free flowing,710,train
12636,DY0Hab2AGNCT3NoP8rPIoA0,Norman Niles #4,time_segment_711_Norman Niles #4_congestion_en...,time_segment_711_Norman Niles #4_congestion_ex...,normanniles4/normanniles4_2025-10-20-17-57-45.mp4,2025-10-20 17:57:45,2025-10-20 17:57:43,2025-10-20 17:58:42,2025-10-20,high,heavy delay,free flowing,711,train
12637,zYkHacmCK7Ov3NoPq7G46QE,Norman Niles #4,time_segment_712_Norman Niles #4_congestion_en...,time_segment_712_Norman Niles #4_congestion_ex...,normanniles4/normanniles4_2025-10-20-17-58-45.mp4,2025-10-20 17:58:45,2025-10-20 17:58:43,2025-10-20 17:59:42,2025-10-20,low,free flowing,free flowing,712,train

In [16]:
df[df["date"] == "2025-10-20"][["view_label", "congestion_enter_rating", "congestion_exit_rating", "signaling", ]]

,view_label,congestion_enter_rating,congestion_exit_rating,signaling
0,Norman Niles #1,free flowing,free flowing,none
1,Norman Niles #1,free flowing,free flowing,none
2,Norman Niles #1,free flowing,free flowing,none
3,Norman Niles #1,free flowing,free flowing,none
4,Norman Niles #1,free flowing,free flowing,none
...,...,...,...,...
12633,Norman Niles #4,free flowing,free flowing,none
12634,Norman Niles #4,light delay,free flowing,none
12635,Norman Niles #4,free flowing,free flowing,none
12636,Norman Niles #4,heavy delay,free flowing,high
12637,Norman Niles #4,free flowing,free flowing,low

In [5]:
df[0:1].to_dict()

{'responseId': {0: 'zYkHaeOdB7XOnvgP3YW5kQs'},
 'view_label': {0: 'Norman Niles #1'},
 'ID_enter': {0: 'time_segment_0_Norman Niles #1_congestion_enter_rating'},
 'ID_exit': {0: 'time_segment_0_Norman Niles #1_congestion_exit_rating'},
 'videos': {0: 'normanniles1/normanniles1_2025-10-20-06-00-45.mp4'},
 'video_time': {0: '2025-10-20 06:00:45'},
 'datetimestamp_start': {0: '2025-10-20 06:00:45'},
 'datetimestamp_end': {0: '2025-10-20 06:01:44'},
 'date': {0: '2025-10-20'},
 'signaling': {0: 'none'},
 'congestion_enter_rating': {0: 'free flowing'},
 'congestion_exit_rating': {0: 'free flowing'},
 'time_segment_id': {0: 0},
 'cycle_phase': {0: 'train'}}